import Link from "next/link";
import { requireUser } from "@/lib/rbac/guard";
import { organisationLife } from "@/lib/people/organisation";
import { milestoneAction,recogniseAction,ritualAction,updateProfileAction } from "./actions";
const input="w-full rounded-xl border border-surface-border bg-surface-raised px-3 py-2 text-sm";
export default async function CulturePage(){const user=await requireUser();const life=await organisationLife(user.id);const me=life.people.find(p=>p.userId===user.id);const owner=user.role==="OWNER";return <div className="mx-auto max-w-7xl space-y-7"><header className="rounded-[30px] bg-brand px-7 py-8 text-white"><Link href="/people" className="text-xs text-white/70">← Remote operations</Link><p className="mt-5 text-[10px] font-semibold uppercase tracking-[.2em] text-white/60">People · Organisational life</p><h1 className="mt-2 font-display text-4xl">Know where you belong and who can help.</h1><p className="mt-3 max-w-3xl text-sm text-white/70">Useful profiles and specific contribution—not followers, popularity, leaderboards or invented authority.</p></header>
<div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><section className="rounded-3xl border border-surface-border bg-surface-raised p-6"><h2 className="font-display text-2xl">My work profile</h2><p className="mt-1 text-xs text-ink-muted">Experience: {me?.experience??"STAFF"}. This shapes context only; it grants no SecurePay status or entitlement.</p><form action={updateProfileAction} className="mt-4 space-y-3"><select name="departmentId" defaultValue={life.departments.find(d=>d.key===me?.departmentKey)?.id??""} className={input}><option value="">Cross-functional</option>{life.departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><textarea name="introduction" maxLength={600} defaultValue={me?.introduction} placeholder="How I contribute" className={input}/><input name="responsibilities" defaultValue={me?.responsibilities.join(", ")} placeholder="Responsibilities, comma separated" className={input}/><input name="skills" defaultValue={me?.skills.join(", ")} placeholder="Skills, comma separated" className={input}/><input name="helpWith" maxLength={300} defaultValue={me?.helpWith} placeholder="Come to me for…" className={input}/><button className="rounded-full bg-brand px-4 py-2 text-sm font-semibold text-white">Save useful profile</button></form></section>
<section className="rounded-3xl border border-surface-border bg-surface-raised p-6"><h2 className="font-display text-2xl">Organisation map</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{life.departments.map(d=><div key={d.id} className="rounded-2xl bg-surface p-4"><p className="font-semibold">{d.name}</p><p className="mt-1 text-xs text-ink-muted">{d.purpose}</p><div className="mt-3 space-y-2">{life.people.filter(p=>p.departmentKey===d.key).map(p=><div key={p.userId} className="border-t border-surface-border pt-2"><p className="text-sm font-medium">{p.name} · {p.experience}</p><p className="text-xs text-ink-faint">{p.helpWith||p.skills.join(", ")||"Profile still growing"} · {p.presenceStatus} {p.timezone}</p></div>)}</div></div>)}</div></section></div>
<div className="grid gap-6 lg:grid-cols-3"><section className="rounded-3xl border border-surface-border bg-surface-raised p-6"><h2 className="font-display text-2xl">Recognise contribution</h2><form action={recogniseAction} className="mt-3 space-y-2"><select name="recipientUserId" className={input}>{life.people.filter(p=>p.userId!==user.id).map(p=><option key={p.userId} value={p.userId}>{p.name}</option>)}</select><textarea name="contribution" required minLength={8} maxLength={500} placeholder="Name the specific help or outcome" className={input}/><button className="rounded-xl bg-brand px-3 py-2 text-xs font-semibold text-white">Recognise</button></form><div className="mt-4 space-y-3">{life.recognition.map(r=><article key={r.id} className="rounded-xl bg-surface p-3 text-xs"><p className="font-semibold">{r.recipientName}</p><p className="mt-1 text-ink-muted">{r.contribution}</p><p className="mt-1 text-ink-faint">From {r.givenByName??"Former teammate"}</p></article>)}</div></section>
<section className="rounded-3xl border border-surface-border bg-surface-raised p-6"><h2 className="font-display text-2xl">Milestones</h2>{owner?<form action={milestoneAction} className="mt-3 space-y-2"><input name="title" required className={input} placeholder="What happened"/><input type="date" name="happenedOn" required className={input}/><textarea name="meaning" required minLength={8} className={input} placeholder="Why it matters"/><button className="rounded-xl bg-brand px-3 py-2 text-xs font-semibold text-white">Record milestone</button></form>:null}<div className="mt-4 space-y-3">{life.milestones.map(m=><article key={m.id}><p className="text-sm font-semibold">{m.title}</p><p className="text-xs text-ink-muted">{m.meaning}</p><p className="text-[10px] text-ink-faint">{m.happenedOn}</p></article>)}</div></section>
<section className="rounded-3xl border border-surface-border bg-surface-raised p-6"><h2 className="font-display text-2xl">Community rituals</h2>{owner?<form action={ritualAction} className="mt-3 space-y-2"><input name="name" required className={input} placeholder="Ritual name"/><input name="cadence" required className={input} placeholder="e.g. Fridays at 16:00 EAT"/><textarea name="purpose" required minLength={8} className={input} placeholder="Purpose"/><button className="rounded-xl bg-brand px-3 py-2 text-xs font-semibold text-white">Create ritual</button></form>:null}<div className="mt-4 space-y-3">{life.rituals.map(r=><article key={r.id} className="rounded-xl bg-surface p-3"><p className="text-sm font-semibold">{r.name}</p><p className="text-xs text-ink-muted">{r.purpose}</p><p className="text-[10px] text-brand">{r.cadence}</p></article>)}</div></section></div></div>}
