export interface ReferralRelationshipEvidence {
  relationshipId: string;
  referredKsNumber: string;
  status: string;
  createdAt: string;
  activatedAt: string | null;
  qualifiedAt: string | null;
  rewardAmountMinor: number | null;
  rewardCurrency: string | null;
  pricingVersion: string | null;
  referralRuleVersion: string | null;
  qualificationExplanation: string | null;
  settlementEvidenceReference: string | null;
}

export interface ReferralHistoryEvidence {
  referralCode: string;
  totalReferred: number;
  activatedOrLaterCount: number;
  relationships: ReferralRelationshipEvidence[];
}

export type MarketEconomyAuthorityErrorCode =
  | "UNAUTHENTICATED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "UPSTREAM_ERROR";

export class MarketEconomyAuthorityError extends Error {
  constructor(
    public readonly code: MarketEconomyAuthorityErrorCode,
    public readonly status: number,
    message: string
  ) {
    super(message);
    this.name = "MarketEconomyAuthorityError";
  }
}

export interface ReferralAuthorityPort {
  getMyReferralHistory(): Promise<ReferralHistoryEvidence>;
}

export interface ConfirmedRewardEvidenceTotal {
  amountMinor: number;
  currency: string;
  relationshipCount: number;
}

/**
 * Adds only reward amounts that SecurePay already persisted as qualification
 * evidence on the caller's referral relationships. This is a UI aggregation,
 * not a reward formula, balance, payout calculation or lifetime-share engine.
 *
 * Mixed currencies or unsafe numeric values intentionally return null rather
 * than silently producing a misleading total.
 */
export function totalConfirmedReferralRewardEvidence(
  history: ReferralHistoryEvidence
): ConfirmedRewardEvidenceTotal | null {
  const qualified = history.relationships.filter(
    (relationship) =>
      relationship.rewardAmountMinor !== null &&
      relationship.rewardCurrency !== null
  );

  const first = qualified[0];
  if (!first?.rewardCurrency) return null;

  const currencies = new Set(qualified.map((relationship) => relationship.rewardCurrency));
  if (currencies.size !== 1) return null;

  let amountMinor = 0;
  for (const relationship of qualified) {
    const amount = relationship.rewardAmountMinor;
    if (
      amount === null ||
      !Number.isSafeInteger(amount) ||
      amount < 0 ||
      !Number.isSafeInteger(amountMinor + amount)
    ) {
      return null;
    }
    amountMinor += amount;
  }

  return {
    amountMinor,
    currency: first.rewardCurrency,
    relationshipCount: qualified.length,
  };
}

export const lifetimeShareAuthority = {
  status: "NOT_BACKEND_SUPPORTED" as const,
  title: "Lifetime Market Share",
  targetRule:
    "Target commercial model: a Plug keeps a qualifying 10% share of the platform fee generated by the relationships they originated for life.",
  currentTruth:
    "SecurePay currently proves referral provenance and settlement-backed KeyContract reward evidence. It also has a separate one-time month-10 subscription retention entitlement in the backend domain. It does not yet expose or calculate a recurring lifetime 10% residual across future platform activity.",
  requiredBackendDecision:
    "Before a lifetime amount can exist, SecurePay must define which platform-fee families qualify, when qualification occurs, how reversals/exceptions affect entitlement, and expose immutable participant-safe evidence. Outreach must then display that evidence rather than calculate entitlement itself.",
};

export const retentionRewardAuthority = {
  status: "BACKEND_DOMAIN_NOT_HTTP_EXPOSED" as const,
  title: "10th-month retention reward",
  currentTruth:
    "SecurePay backend authority awards the actual successfully collected tenth subscription fee once a referred KS Number completes 10 consecutive paid active months. Outreach does not yet have a participant HTTP endpoint to read that progress or entitlement.",
};
