"use server";
import { revalidatePath } from "next/cache";
import { requireUser } from "@/lib/rbac/guard";
import { createDutyRotation, scheduleCoverage, updateMyPresence, type PresenceStatus } from "@/lib/people/remote-team";
const PRESENCE=new Set<PresenceStatus>(["AVAILABLE","FOCUSED","AWAY","OFFLINE"]);
export async function updatePresenceAction(formData:FormData){const user=await requireUser();const status=value(formData,"presenceStatus") as PresenceStatus;if(!PRESENCE.has(status))throw new Error("Presence status is invalid");await updateMyPresence({userId:user.id,timezone:required(formData,"timezone"),languages:required(formData,"languages").split(","),available:formData.get("available")==="on",presenceStatus:status,presenceNote:value(formData,"presenceNote"),workingDays:formData.getAll("workingDays").map(Number),localStart:required(formData,"localStart"),localEnd:required(formData,"localEnd")});revalidatePath("/people");revalidatePath("/today");}
export async function scheduleCoverageAction(formData:FormData){const user=await requireUser();await scheduleCoverage({actorUserId:user.id,userId:required(formData,"userId"),queueKey:required(formData,"queueKey"),startsAt:dateValue(formData,"startsAt"),endsAt:dateValue(formData,"endsAt"),responsibility:value(formData,"responsibility")});revalidatePath("/people");}
export async function createRotationAction(formData:FormData){const user=await requireUser();await createDutyRotation({actorUserId:user.id,name:required(formData,"name"),queueKey:required(formData,"queueKey"),primaryUserId:required(formData,"primaryUserId"),backupUserId:value(formData,"backupUserId")||null,timezone:required(formData,"timezone"),cadenceDays:Number(required(formData,"cadenceDays")),nextHandoffAt:dateValue(formData,"nextHandoffAt")});revalidatePath("/people");}
function value(f:FormData,k:string){const x=f.get(k);return typeof x==="string"?x.trim():"";}function required(f:FormData,k:string){const x=value(f,k);if(!x)throw new Error(`${k} is required`);return x;}function dateValue(f:FormData,k:string){const d=new Date(required(f,k));if(Number.isNaN(d.valueOf()))throw new Error(`${k} is invalid`);return d;}
