import { randomUUID } from "node:crypto";
import { sql } from "drizzle-orm";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { db } from "@/lib/db";
import { createDutyRotation,handoverWork,listDutyRotations,listTeamPresence,listUpcomingCoverage,listWorkHandovers,scheduleCoverage,updateMyPresence } from "@/lib/people/remote-team";
import { createWorkItem,getWorkItem } from "@/lib/work/work-engine";
const run=randomUUID().slice(0,8);let owner="",from="",to="";const work:string[]=[];
function rows<T>(r:unknown):T[]{return (r as {rows?:T[]}).rows??[];}async function staff(name:string,role="STRATEGIST"){const x=rows<{id:string}>(await db.execute(sql`INSERT INTO users(email,password_hash,name,role,active) VALUES(${`remote-${run}-${name}@test.local`},'x',${name},${role}::role,true) RETURNING id::text`))[0];if(!x)throw new Error("setup");return x.id;}
beforeAll(async()=>{owner=await staff("Owner","OWNER");from=await staff("Amina");to=await staff("Kamau");});
afterAll(async()=>{for(const id of work)await db.execute(sql`DELETE FROM work_items WHERE id=${id}::uuid`);await db.execute(sql`DELETE FROM team_coverage_shifts WHERE created_by_user_id=${owner}::uuid`);await db.execute(sql`DELETE FROM team_duty_rotations WHERE created_by_user_id=${owner}::uuid`);await db.execute(sql`DELETE FROM users WHERE id IN(${owner}::uuid,${from}::uuid,${to}::uuid)`);});
describe("True North Phase 6 remote team",()=>{
it("publishes bounded working presence without changing staff authority",async()=>{await updateMyPresence({userId:from,timezone:"Africa/Nairobi",languages:["en","sw"],available:true,presenceStatus:"FOCUSED",presenceNote:"Settlement handover at 17:00",workingDays:[1,2,3,4,5],localStart:"08:00",localEnd:"17:00"});const p=(await listTeamPresence(from)).find(x=>x.userId===from);expect(p).toEqual(expect.objectContaining({timezone:"Africa/Nairobi",presenceStatus:"FOCUSED",languages:["en","sw"]}));});
it("records an immutable-context handover and transfers one accountable owner",async()=>{const id=await createWorkItem({actorUserId:from,workType:"TASK",title:`Remote handover ${run}`,ownerUserId:from,nextAction:"Check current evidence."});work.push(id);await handoverWork({actorUserId:from,workItemId:id,toUserId:to,summary:"Evidence reviewed; one provider reply is pending.",nextAction:"Review provider reply and record the outcome."});expect((await getWorkItem(to,id)).ownerUserId).toBe(to);expect(await listWorkHandovers(to,id)).toEqual([expect.objectContaining({fromName:"Amina",toName:"Kamau"})]);await expect(handoverWork({actorUserId:from,workItemId:id,toUserId:owner,summary:"Replay",nextAction:"Should fail"})).rejects.toThrow("current active owner");});
it("lets Owner coordinate coverage and rotations without creating payroll authority",async()=>{const start=new Date(Date.now()+3600000),end=new Date(start.getTime()+28800000);await scheduleCoverage({actorUserId:owner,userId:from,queueKey:"TRADER_SUPPORT",startsAt:start,endsAt:end,responsibility:"First response and explicit handover."});expect((await listUpcomingCoverage(from)).some(x=>x.userId===from)).toBe(true);await expect(scheduleCoverage({actorUserId:from,userId:to,queueKey:"GENERAL",startsAt:start,endsAt:end})).rejects.toThrow("Owner oversight");await createDutyRotation({actorUserId:owner,name:`Weekend support ${run}`,queueKey:"TRADER_SUPPORT",primaryUserId:from,backupUserId:to,timezone:"Africa/Nairobi",cadenceDays:7,nextHandoffAt:start});expect((await listDutyRotations(to)).some(x=>x.name.includes(run))).toBe(true);});
});
