import { sql } from "drizzle-orm";
import { db } from "@/lib/db";

export type Experience="STAFF"|"PLUG"|"MASTER"|"DIRECTOR"|"INVESTOR";
export interface PersonProfile{userId:string;name:string;role:string;departmentKey:string|null;departmentName:string|null;experience:Experience;introduction:string;responsibilities:string[];skills:string[];helpWith:string;presenceStatus:string;timezone:string;}
export interface Recognition{id:string;recipientName:string;givenByName:string|null;contribution:string;createdAt:Date;}
export interface Milestone{id:string;title:string;meaning:string;happenedOn:string;}
export interface Ritual{id:string;name:string;purpose:string;cadence:string;}

export async function organisationLife(userId:string){await active(userId);await db.execute(sql`INSERT INTO people_profiles(user_id,experience) SELECT id,CASE WHEN role IN('OWNER','GROWTH_DIRECTOR') THEN 'DIRECTOR'::organisation_experience ELSE 'STAFF'::organisation_experience END FROM users WHERE active=TRUE ON CONFLICT(user_id) DO NOTHING`);const [people,departments,recognition,milestones,rituals]=await Promise.all([
db.execute(sql`SELECT u.id::text AS "userId",u.name,u.role::text AS role,d.department_key AS "departmentKey",d.name AS "departmentName",p.experience::text AS experience,p.introduction,p.responsibilities,p.skills,p.help_with AS "helpWith",COALESCE(r.presence_status::text,'OFFLINE') AS "presenceStatus",COALESCE(r.timezone,'UTC') AS timezone FROM users u JOIN people_profiles p ON p.user_id=u.id LEFT JOIN organisation_departments d ON d.id=p.department_id LEFT JOIN work_routing_profiles r ON r.user_id=u.id WHERE u.active=TRUE ORDER BY d.name NULLS LAST,u.name`),
db.execute(sql`SELECT id::text AS id,department_key AS key,name,purpose FROM organisation_departments WHERE active=TRUE ORDER BY name`),
db.execute(sql`SELECT x.id::text AS id,recipient.name AS "recipientName",giver.name AS "givenByName",x.contribution,x.created_at AS "createdAt" FROM people_recognition x JOIN users recipient ON recipient.id=x.recipient_user_id LEFT JOIN users giver ON giver.id=x.given_by_user_id ORDER BY x.created_at DESC LIMIT 50`),
db.execute(sql`SELECT id::text AS id,title,meaning,happened_on::text AS "happenedOn" FROM organisation_milestones ORDER BY happened_on DESC LIMIT 30`),
db.execute(sql`SELECT id::text AS id,name,purpose,cadence FROM organisation_rituals WHERE active=TRUE ORDER BY name`)]);
return {people:rows<PersonProfile>(people),departments:rows<{id:string;key:string;name:string;purpose:string}>(departments),recognition:rows<Recognition>(recognition).map(x=>({...x,createdAt:new Date(x.createdAt)})),milestones:rows<Milestone>(milestones),rituals:rows<Ritual>(rituals)};}

export async function updateProfile(input:{userId:string;departmentId?:string|null;introduction?:string;responsibilities:string[];skills:string[];helpWith?:string}){await active(input.userId);const responsibilities=list(input.responsibilities,12,80),skills=list(input.skills,20,60);await db.execute(sql`INSERT INTO people_profiles(user_id,department_id,introduction,responsibilities,skills,help_with) VALUES(${input.userId}::uuid,${input.departmentId??null}::uuid,${text(input.introduction??"",0,600,"Introduction")},string_to_array(${responsibilities.join("\u001f")},chr(31)),string_to_array(${skills.join("\u001f")},chr(31)),${text(input.helpWith??"",0,300,"Help offer")}) ON CONFLICT(user_id) DO UPDATE SET department_id=excluded.department_id,introduction=excluded.introduction,responsibilities=excluded.responsibilities,skills=excluded.skills,help_with=excluded.help_with,updated_at=now()`);}
export async function recognise(input:{actorUserId:string;recipientUserId:string;contribution:string}){await active(input.actorUserId);await active(input.recipientUserId);if(input.actorUserId===input.recipientUserId)throw new Error("Recognition must come from another person");await db.execute(sql`INSERT INTO people_recognition(recipient_user_id,given_by_user_id,contribution) VALUES(${input.recipientUserId}::uuid,${input.actorUserId}::uuid,${text(input.contribution,8,500,"Contribution")})`);}
export async function addMilestone(input:{actorUserId:string;title:string;meaning:string;happenedOn:string}){await owner(input.actorUserId);if(!/^\d{4}-\d{2}-\d{2}$/.test(input.happenedOn))throw new Error("Milestone date is invalid");await db.execute(sql`INSERT INTO organisation_milestones(title,meaning,happened_on,created_by_user_id) VALUES(${text(input.title,2,140,"Title")},${text(input.meaning,8,1000,"Meaning")},${input.happenedOn}::date,${input.actorUserId}::uuid)`);}
export async function addRitual(input:{actorUserId:string;name:string;purpose:string;cadence:string}){await owner(input.actorUserId);await db.execute(sql`INSERT INTO organisation_rituals(name,purpose,cadence,created_by_user_id) VALUES(${text(input.name,2,120,"Name")},${text(input.purpose,8,600,"Purpose")},${text(input.cadence,2,100,"Cadence")},${input.actorUserId}::uuid)`);}
async function active(id:string){const x=one<{role:string}>(await db.execute(sql`SELECT role::text AS role FROM users WHERE id=${id}::uuid AND active=TRUE`));if(!x)throw new Error("Active staff identity required");return x;}async function owner(id:string){if((await active(id)).role!=="OWNER")throw new Error("Owner oversight is required");}
function list(values:string[],max:number,itemMax:number){const x=Array.from(new Set(values.map(v=>v.trim()).filter(Boolean)));if(x.length>max||x.some(v=>v.length>itemMax))throw new Error("Profile list is invalid");return x;}function text(v:string,min:number,max:number,label:string){const x=v.trim();if(x.length<min||x.length>max)throw new Error(`${label} must be between ${min} and ${max} characters`);return x;}function rows<T>(r:unknown):T[]{return (r as {rows?:T[]}).rows??[];}function one<T>(r:unknown):T|undefined{return rows<T>(r)[0];}
