import { sql } from "drizzle-orm";
import { db } from "@/lib/db";

export type PresenceStatus = "AVAILABLE" | "FOCUSED" | "AWAY" | "OFFLINE";
export interface TeamPresence { userId:string; name:string; role:string; timezone:string; languages:string[]; available:boolean; presenceStatus:PresenceStatus; presenceNote:string; presenceUpdatedAt:Date; workingDays:number[]; localStart:string; localEnd:string; activeWork:number; }
export interface CoverageShift { id:string; userId:string; userName:string; queueKey:string; queueName:string; startsAt:Date; endsAt:Date; status:string; responsibility:string; }
export interface DutyRotation { id:string; name:string; queueKey:string; primaryName:string; backupName:string|null; timezone:string; cadenceDays:number; nextHandoffAt:Date; }
export interface WorkHandover { id:string; workItemId:string; fromName:string; toName:string; summary:string; nextAction:string; createdAt:Date; }

export async function listTeamPresence(userId:string):Promise<TeamPresence[]> {
  await requireActive(userId);
  const result=await db.execute(sql`SELECT u.id::text AS "userId",u.name,u.role::text AS role,r.timezone,r.languages,r.available,r.presence_status::text AS "presenceStatus",r.presence_note AS "presenceNote",r.presence_updated_at AS "presenceUpdatedAt",r.working_days AS "workingDays",r.local_start::text AS "localStart",r.local_end::text AS "localEnd",(SELECT count(*)::int FROM work_items w WHERE w.owner_user_id=u.id AND w.status NOT IN ('DONE','CANCELLED')) AS "activeWork" FROM users u JOIN work_routing_profiles r ON r.user_id=u.id WHERE u.active=TRUE ORDER BY CASE r.presence_status WHEN 'AVAILABLE' THEN 0 WHEN 'FOCUSED' THEN 1 WHEN 'AWAY' THEN 2 ELSE 3 END,u.name`);
  return rows<TeamPresence>(result).map(x=>({...x,presenceUpdatedAt:date(x.presenceUpdatedAt),activeWork:Number(x.activeWork)}));
}

export async function updateMyPresence(input:{userId:string;timezone:string;languages:string[];available:boolean;presenceStatus:PresenceStatus;presenceNote?:string;workingDays:number[];localStart:string;localEnd:string}):Promise<void>{
  await requireActive(input.userId); const timezone=token(input.timezone,80,"Timezone"); const languages=Array.from(new Set(input.languages.map(v=>v.trim().toLowerCase()).filter(v=>/^[a-z]{2,8}(-[a-z0-9]{2,8})?$/.test(v)))); if(!languages.length)throw new Error("At least one valid language is required");
  const days=Array.from(new Set(input.workingDays)); if(!days.length||days.some(v=>!Number.isInteger(v)||v<0||v>6))throw new Error("Working days are invalid"); const note=text(input.presenceNote??"",0,240,"Presence note"); if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(input.localStart)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(input.localEnd)||input.localStart>=input.localEnd)throw new Error("Working hours are invalid");
  await db.execute(sql`UPDATE work_routing_profiles SET timezone=${timezone},languages=string_to_array(${languages.join(",")},','),available=${input.available},presence_status=${input.presenceStatus}::team_presence_status,presence_note=${note},working_days=string_to_array(${days.join(",")},',')::integer[],local_start=${input.localStart}::time,local_end=${input.localEnd}::time,presence_updated_at=now(),updated_at=now() WHERE user_id=${input.userId}::uuid`);
}

export async function scheduleCoverage(input:{actorUserId:string;userId:string;queueKey:string;startsAt:Date;endsAt:Date;responsibility?:string}):Promise<string>{
  await requireOwner(input.actorUserId); await requireActive(input.userId); if(!validDate(input.startsAt)||!validDate(input.endsAt)||input.endsAt<=input.startsAt)throw new Error("Coverage window is invalid");
  const queue=one<{id:string}>(await db.execute(sql`SELECT id::text AS id FROM work_queues WHERE queue_key=${token(input.queueKey,80,"Queue")} AND active=TRUE LIMIT 1`)); if(!queue)throw new Error("Work queue is unavailable");
  const inserted=one<{id:string}>(await db.execute(sql`INSERT INTO team_coverage_shifts(user_id,queue_id,starts_at,ends_at,responsibility,created_by_user_id) VALUES(${input.userId}::uuid,${queue.id}::uuid,${input.startsAt},${input.endsAt},${text(input.responsibility??"",0,500,"Responsibility")},${input.actorUserId}::uuid) RETURNING id::text`)); if(!inserted)throw new Error("Coverage shift could not be scheduled"); return inserted.id;
}

export async function listUpcomingCoverage(userId:string):Promise<CoverageShift[]>{await requireActive(userId);return rows<CoverageShift>(await db.execute(sql`SELECT s.id::text AS id,s.user_id::text AS "userId",u.name AS "userName",q.queue_key AS "queueKey",q.name AS "queueName",s.starts_at AS "startsAt",s.ends_at AS "endsAt",s.status::text AS status,s.responsibility FROM team_coverage_shifts s JOIN users u ON u.id=s.user_id JOIN work_queues q ON q.id=s.queue_id WHERE s.status IN('SCHEDULED','ACTIVE') AND s.ends_at>now() ORDER BY s.starts_at LIMIT 100`)).map(x=>({...x,startsAt:date(x.startsAt),endsAt:date(x.endsAt)}));}

export async function handoverWork(input:{actorUserId:string;workItemId:string;toUserId:string;summary:string;nextAction:string}):Promise<string>{
  await requireActive(input.actorUserId); await requireActive(input.toUserId); if(input.actorUserId===input.toUserId)throw new Error("Choose another team member for handover");
  return db.transaction(async tx=>{const current=one<{ownerUserId:string|null;status:string}>(await tx.execute(sql`SELECT owner_user_id::text AS "ownerUserId",status::text AS status FROM work_items WHERE id=${input.workItemId}::uuid FOR UPDATE`));if(!current||current.ownerUserId!==input.actorUserId||['DONE','CANCELLED'].includes(current.status))throw new Error("Only the current active owner may hand over this work");const incident=one(await tx.execute(sql`SELECT 1 FROM operations_incidents WHERE work_item_id=${input.workItemId}::uuid LIMIT 1`));if(incident)throw new Error("Incident command must transfer incident responsibility");const inserted=one<{id:string}>(await tx.execute(sql`INSERT INTO work_handovers(work_item_id,from_user_id,to_user_id,summary,next_action) VALUES(${input.workItemId}::uuid,${input.actorUserId}::uuid,${input.toUserId}::uuid,${text(input.summary,2,4000,"Handover summary")},${text(input.nextAction,2,500,"Next action")}) RETURNING id::text`));if(!inserted)throw new Error("Handover could not be recorded");await tx.execute(sql`UPDATE work_items SET owner_user_id=${input.toUserId}::uuid,next_action=${text(input.nextAction,2,500,"Next action")},routing_reason='Explicit remote-team handover',updated_at=now() WHERE id=${input.workItemId}::uuid`);await tx.execute(sql`INSERT INTO work_history(work_item_id,event_type,actor_user_id,metadata) VALUES(${input.workItemId}::uuid,'WORK_HANDED_OVER',${input.actorUserId}::uuid,CAST(${JSON.stringify({handoverId:inserted.id,toUserId:input.toUserId})} AS jsonb))`);return inserted.id;});
}

export async function listWorkHandovers(userId:string,workItemId:string):Promise<WorkHandover[]>{await requireActive(userId);const visible=one(await db.execute(sql`SELECT 1 FROM work_items w WHERE w.id=${workItemId}::uuid AND (w.owner_user_id=${userId}::uuid OR w.created_by_user_id=${userId}::uuid OR EXISTS(SELECT 1 FROM work_collaborators c WHERE c.work_item_id=w.id AND c.user_id=${userId}::uuid) OR EXISTS(SELECT 1 FROM users u WHERE u.id=${userId}::uuid AND u.role='OWNER')) LIMIT 1`));if(!visible)throw new Error("Work item is unavailable");return rows<WorkHandover>(await db.execute(sql`SELECT h.id::text AS id,h.work_item_id::text AS "workItemId",f.name AS "fromName",t.name AS "toName",h.summary,h.next_action AS "nextAction",h.created_at AS "createdAt" FROM work_handovers h JOIN users f ON f.id=h.from_user_id JOIN users t ON t.id=h.to_user_id WHERE h.work_item_id=${workItemId}::uuid ORDER BY h.created_at DESC`)).map(x=>({...x,createdAt:date(x.createdAt)}));}

export async function createDutyRotation(input:{actorUserId:string;name:string;queueKey:string;primaryUserId:string;backupUserId?:string|null;timezone:string;cadenceDays:number;nextHandoffAt:Date}):Promise<string>{await requireOwner(input.actorUserId);await requireActive(input.primaryUserId);if(input.backupUserId)await requireActive(input.backupUserId);if(input.backupUserId===input.primaryUserId)throw new Error("Rotation backup must be different");if(!Number.isSafeInteger(input.cadenceDays)||input.cadenceDays<1||input.cadenceDays>90||!validDate(input.nextHandoffAt))throw new Error("Rotation schedule is invalid");const q=one<{id:string}>(await db.execute(sql`SELECT id::text AS id FROM work_queues WHERE queue_key=${token(input.queueKey,80,"Queue")} AND active=TRUE`));if(!q)throw new Error("Work queue is unavailable");const item=one<{id:string}>(await db.execute(sql`INSERT INTO team_duty_rotations(name,queue_id,primary_user_id,backup_user_id,timezone,cadence_days,next_handoff_at,created_by_user_id) VALUES(${text(input.name,2,120,"Rotation name")},${q.id}::uuid,${input.primaryUserId}::uuid,${input.backupUserId??null}::uuid,${token(input.timezone,80,"Timezone")},${input.cadenceDays},${input.nextHandoffAt},${input.actorUserId}::uuid) RETURNING id::text`));if(!item)throw new Error("Rotation could not be created");return item.id;}
export async function listDutyRotations(userId:string):Promise<DutyRotation[]>{await requireActive(userId);return rows<DutyRotation>(await db.execute(sql`SELECT r.id::text AS id,r.name,q.queue_key AS "queueKey",p.name AS "primaryName",b.name AS "backupName",r.timezone,r.cadence_days AS "cadenceDays",r.next_handoff_at AS "nextHandoffAt" FROM team_duty_rotations r JOIN work_queues q ON q.id=r.queue_id JOIN users p ON p.id=r.primary_user_id LEFT JOIN users b ON b.id=r.backup_user_id WHERE r.active=TRUE ORDER BY r.next_handoff_at`)).map(x=>({...x,cadenceDays:Number(x.cadenceDays),nextHandoffAt:date(x.nextHandoffAt)}));}

async function requireActive(id:string){const x=one<{role:string}>(await db.execute(sql`SELECT role::text AS role FROM users WHERE id=${id}::uuid AND active=TRUE LIMIT 1`));if(!x)throw new Error("Active staff identity required");return x;}
async function requireOwner(id:string){const x=await requireActive(id);if(x.role!=="OWNER")throw new Error("Owner oversight is required");}
function text(v:string,min:number,max:number,label:string){const x=v.trim();if(x.length<min||x.length>max)throw new Error(`${label} must be between ${min} and ${max} characters`);return x;}
function token(v:string,max:number,label:string){const x=v.trim();if(!x||x.length>max||!/^[A-Za-z0-9_+\-/]+$/.test(x))throw new Error(`${label} is invalid`);return x;}
function validDate(v:Date){return v instanceof Date&&!Number.isNaN(v.valueOf());} function date(v:Date|string){return v instanceof Date?v:new Date(v);} function rows<T=Record<string,unknown>>(r:unknown):T[]{return (r as {rows?:T[]}).rows??[];} function one<T=Record<string,unknown>>(r:unknown):T|undefined{return rows<T>(r)[0];}
